import FreedbackWidget from "./FreedbackWidget.jsx";

// Realistic-looking mock endpoints. The in-browser mock backend recognises them
// by path (/annotations/ for publish, /index for read) — the host is cosmetic,
// chosen to read like a real feedback + collection deployment in the snippets.
const PUBLISH = "https://feedback.demo.freedback.net/annotations/";
const READ = "https://collection.demo.freedback.net/index";

// Each widget kind gets its OWN target so aggregates don't cross-count: the
// rating widgets all aggregate any `*Rating` body via `ratingValue`, so a shared
// target would make the thumb count star/scalar ratings (this is exactly why
// the e2e harness isolates kinds with `#fragment` targets).
export const TARGETS = {
  stars: "https://example.com/products/aurora-headphones",
  thumb: "https://example.com/articles/federated-feedback",
  scalar: "https://example.com/talks/rdf-in-the-browser",
  comment: "https://example.com/products/aurora-headphones#discussion",
  tag: "https://example.com/products/aurora-headphones#tags",
  signStars: "https://example.com/demo/self-signed",
  tokenStars: "https://example.com/demo/oauth-bearer",
};

function Snippet({ code }) {
  return (
    <details className="snippet">
      <summary>Embed code</summary>
      <pre>
        <code>{code}</code>
      </pre>
    </details>
  );
}

function Card({ title, blurb, children, snippet }) {
  return (
    <section className="card">
      <h3>{title}</h3>
      {blurb && <p className="blurb">{blurb}</p>}
      <div className="widget-host">{children}</div>
      {snippet && <Snippet code={snippet} />}
    </section>
  );
}

export default function App() {
  return (
    <main>
      <header className="hero">
        <p className="home-link">
          <a href="/">← freedback.net</a>
        </p>
        <h1>Freedback — live widget showcase</h1>
        <p className="sub">
          A federated, open protocol for typed feedback on anything with a URI —
          carried as W3C Web Annotations. Below are the <strong>shipped</strong>{" "}
          drop-in widgets, live.
        </p>
      </header>

      <div className="banner" role="status">
        <strong>Demo mode.</strong> There is no live Freedback server here. Every
        response is <em>simulated in your browser</em> by an in-memory mock
        backend — nothing is persisted, and nothing is sent anywhere. The
        self-signed (<code>data-sign</code>) keypair is generated by WebCrypto and
        stays in this browser's IndexedDB. Click a star, post a comment, add a
        tag — the aggregate updates live, exactly as it would against a real
        server.
      </div>

      <section className="intro">
        <p>
          These are vanilla Web Components (no framework) embedded straight into
          this React page. Each one reads an aggregate from a collection server
          (<code>data-read</code>) and publishes a W3C Web Annotation to a
          feedback server (<code>data-publish</code>). Two ways to authorize a
          write:
        </p>
        <ul>
          <li>
            <code>data-sign</code> — the page holds a portable P-256 key
            (WebCrypto, kept in IndexedDB) and attaches a detached ES256
            signature. This is the <em>federating</em> identity.
          </li>
          <li>
            <code>data-token</code> — an OAuth bearer. The siloed, non-federating
            identity. (<code>data-sign</code> wins if both are present.)
          </li>
        </ul>
      </section>

      <h2>The five widget kinds</h2>
      <p className="section-note">
        Each is shown in read + publish mode using the self-signed
        (<code>data-sign</code>) path.
      </p>

      <Card
        title="Stars"
        blurb="A 1–5 star rating (freedback:StarRating). Click a star to rate; the average and count update."
        snippet={`<freedback-stars data-sign
  data-target="${TARGETS.stars}"
  data-read="${READ}"
  data-publish="${PUBLISH}"></freedback-stars>`}
      >
        <FreedbackWidget
          kind="freedback-stars"
          sign
          target={TARGETS.stars}
          read={READ}
          publish={PUBLISH}
        />
      </Card>

      <Card
        title="Thumbs"
        blurb="A binary 👍 / 👎 (freedback:ThumbRating) — the only net-new vocabulary in the protocol."
        snippet={`<freedback-thumb data-sign
  data-target="${TARGETS.thumb}"
  data-read="${READ}"
  data-publish="${PUBLISH}"></freedback-thumb>`}
      >
        <FreedbackWidget
          kind="freedback-thumb"
          sign
          target={TARGETS.thumb}
          read={READ}
          publish={PUBLISH}
        />
      </Card>

      <Card
        title="Scalar (custom scale 0–10)"
        blurb="A continuous bounded rating (freedback:ScalarRating). The body carries the scale so SHACL can validate it."
        snippet={`<freedback-scalar data-sign
  data-worst="0" data-best="10" data-step="1"
  data-target="${TARGETS.scalar}"
  data-read="${READ}"
  data-publish="${PUBLISH}"></freedback-scalar>`}
      >
        <FreedbackWidget
          kind="freedback-scalar"
          sign
          data-worst="0"
          data-best="10"
          data-step="1"
          target={TARGETS.scalar}
          read={READ}
          publish={PUBLISH}
        />
      </Card>

      <Card
        title="Comments"
        blurb="Free-text feedback (oa:TextualBody + oa:commenting). Posted comments appear in the list."
        snippet={`<freedback-comment data-sign
  data-target="${TARGETS.comment}"
  data-read="${READ}"
  data-publish="${PUBLISH}"></freedback-comment>`}
      >
        <FreedbackWidget
          kind="freedback-comment"
          sign
          target={TARGETS.comment}
          read={READ}
          publish={PUBLISH}
        />
      </Card>

      <Card
        title="Tags"
        blurb="One tag per submission (oa:TextualBody + oa:tagging). Distinct tags render as chips, with counts."
        snippet={`<freedback-tag data-sign
  data-target="${TARGETS.tag}"
  data-read="${READ}"
  data-publish="${PUBLISH}"></freedback-tag>`}
      >
        <FreedbackWidget
          kind="freedback-tag"
          sign
          target={TARGETS.tag}
          read={READ}
          publish={PUBLISH}
        />
      </Card>

      <h2>The two auth paths</h2>

      <Card
        title="Self-signed (data-sign) — the federating identity"
        blurb="WebCrypto generates a P-256 key, kept in this browser's IndexedDB. Each annotation carries a detached ES256 signature over its RFC 8785 canonical bytes — the portable identity that federates across servers. No token needed."
        snippet={`<freedback-stars data-sign
  data-target="${TARGETS.signStars}"
  data-read="${READ}"
  data-publish="${PUBLISH}"></freedback-stars>`}
      >
        <FreedbackWidget
          kind="freedback-stars"
          sign
          target={TARGETS.signStars}
          read={READ}
          publish={PUBLISH}
        />
      </Card>

      <Card
        title="OAuth bearer (data-token) — the siloed identity"
        blurb="A bearer token authorizes the write under an app-managed, non-federating identity. The mock backend accepts the demo token without verifying it."
        snippet={`<freedback-stars
  data-token="demo-oauth-bearer-token"
  data-target="${TARGETS.tokenStars}"
  data-read="${READ}"
  data-publish="${PUBLISH}"></freedback-stars>`}
      >
        <FreedbackWidget
          kind="freedback-stars"
          token="demo-oauth-bearer-token"
          target={TARGETS.tokenStars}
          read={READ}
          publish={PUBLISH}
        />
      </Card>

      <h2>Read-only</h2>
      <Card
        title="Read-only (no data-publish)"
        blurb="With only data-read, the widget renders the aggregate and disables submission — no auth required."
        snippet={`<freedback-stars
  data-target="${TARGETS.stars}"
  data-read="${READ}"></freedback-stars>`}
      >
        <FreedbackWidget kind="freedback-stars" target={TARGETS.stars} read={READ} />
      </Card>

      <footer>
        <p>
          Protocol artifacts (stable URLs):{" "}
          <a href="/ns/context.jsonld">@context</a> ·{" "}
          <a href="/ns/freedback.ttl">vocabulary</a> ·{" "}
          <a href="/ns/shapes.ttl">SHACL shapes</a> ·{" "}
          <a href="/profile/1">validation profile</a>
        </p>
        <p>
          The drop-in widget script: <a href="/widgets/freedback-widgets.js">freedback-widgets.js</a>{" "}
          (and the original <a href="/widgets/demo.html">static demo</a>).
        </p>
        <p>
          Source &amp; docs:{" "}
          <a href="https://github.com/victorpaleologue/Freedback">
            github.com/victorpaleologue/Freedback
          </a>
        </p>
      </footer>
    </main>
  );
}
