//! Minimal HTTP-date (IMF-fixdate, RFC 7231 §7.1.1.1) formatting/parsing for the
//! `Last-Modified` / `If-Modified-Since` conditional-GET pair.
//!
//! We emit and accept the IMF-fixdate form (`Sun, 06 Nov 1994 08:49:37 GMT`),
//! the preferred and only form a sender is required to produce. The obsolete
//! RFC 850 / asctime forms are not generated by Freedback peers, so we do not
//! parse them — an unrecognized date is simply treated as "no condition".

use time::format_description::BorrowedFormatItem;
use time::macros::format_description;
use time::{OffsetDateTime, PrimitiveDateTime};

/// IMF-fixdate, e.g. `Sun, 06 Nov 1994 08:49:37 GMT`.
const IMF_FIXDATE: &[BorrowedFormatItem<'_>] = format_description!(
    "[weekday repr:short], [day] [month repr:short] [year] [hour]:[minute]:[second] GMT"
);

/// Format a unix timestamp as an IMF-fixdate `Last-Modified` value.
pub fn format(epoch: i64) -> Option<String> {
    OffsetDateTime::from_unix_timestamp(epoch)
        .ok()?
        .format(&IMF_FIXDATE)
        .ok()
}

/// Parse an `If-Modified-Since` IMF-fixdate back to a unix timestamp.
///
/// The IMF-fixdate is always GMT/UTC (the literal `GMT` carries no parsed
/// offset), so we read the civil datetime and assume UTC.
pub fn parse(s: &str) -> Option<i64> {
    PrimitiveDateTime::parse(s.trim(), &IMF_FIXDATE)
        .ok()
        .map(|d| d.assume_utc().unix_timestamp())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_at_second_resolution() {
        // 2026-06-21T10:00:00Z
        let epoch = 1_781_344_800;
        let s = format(epoch).unwrap();
        assert!(s.ends_with(" GMT"), "got {s}");
        assert_eq!(parse(&s), Some(epoch));
    }

    #[test]
    fn known_imf_fixdate_value() {
        // The canonical example from RFC 7231.
        assert_eq!(parse("Sun, 06 Nov 1994 08:49:37 GMT"), Some(784_111_777));
    }

    #[test]
    fn rejects_garbage() {
        assert_eq!(parse("not a date"), None);
    }
}
